### PR TITLE
Add GUI.from_text

### PR DESCRIPTION
**Pull request by DanielSank**
This pull request adds `GUI.from_text(text: str)` which allows creation of a GUI style `Network` directly from a string representation. This compliments the existing API `GUI.__init__(filename: str)` which takes the name of a text file.

### CODE REVIEW

**Comment by DanielSank** [comment]
@mgely Please let me know what you'd like to see added to this pull request in order to get it merged.

**Comment by mgely** [comment]
I'll work on merging it later today, it'll be in the pip install-able version in under a week.
Thanks!

**Comment by mgely** [comment]
BTW: I changed the target of your pull request to the develop branch.

Concerning your code: very function should be unittested, so I tried to add the following code to tests/test_core.py

```python
class CircuitInstantiation (TestCaseAppended):
    '''Test the creation of Qcircuit objects
    '''
    def test_GUI_from_string(self):
        core.GUI.from_string("C;-1,-2;0,-2;1.0e-13;\nJ;-1,-1;0,-1;1.0e-08;\nW;-1,-1;-1,-2;;\nW;0,-1;0,-2;;")
```

And this error popped up (note: same error if I try and use your function from a script)
```
line 1388, in GUI
    def _parse_file(stream: Iterable[str]) -> List[Component]:
NameError: name 'Component' is not defined
```

I guess this has something to do with the Python 3 type annotations.

**Comment by mgely** [comment]
If you could also add get a test working to verify your code that would be fantastic!

**Comment by DanielSank** [comment]
Sure. I just need to figure out how to deal with git across forks. I haven't done that much, but I think I can figure it out.

**Pull request merged**
