### PR TITLE
Finally add the changes properly for the arbitrary dipole

### PR DESCRIPTION
**Pull request by HHeda**

### CODE REVIEW

**Comment by HHeda** [comment]
After several tries I finally manage to create a repository ahead of the master branch that contains the changes I wanted to add. The tutorial works, the branch arbitrary_dipole and test_revert can be deleted (sorry for this mess). We can now work on this branch. The build works too apparently.
However, I don' t really understand what the codecov checks are...

**Comment by mgely** [comment]
Great, the codecov checks what proportion of the codebase is tested.
If changes are made which reduce the proportion of code tested (as is the case here), the codecov checks will fail, it's no too important for the moment.
Thanks! I'll take a look at the code and get back to you.

**Comment by HHeda** [comment]
I made a few modifications, there was a mistake in my tutorial, and I cleaned a bit the way it's stored with the other tutorials. I'm not sure about the way the tests should be performed. For now, the building of a circuit is possible only with the GUI, which makes the tests harder to write. I think there are two things to do to integrate it completely : 

- Make the circuit constructible with the Network function ;
- Allow to give a list of energy and not only labels with the GUI.

I didn't understand how to do this when I was working with it, so I did what seemed simpler to me

**Comment by mgely** [comment]
I agree with what you proposed, and we can now adapted QuCAT to be more friendly to multi-parameter components. Everyhing you mentionned now works.
I also modified the graphics of the new element, let me know if you have any objections.

What is left to do is:
 - Write tests for the new features
 - Add the new tutorial to the website
 - Make a new release of QuCAT

**Pull request merged**
