### PR TITLE
Add arbitrary non linear inductive dipole and third order terms.

### PR DESCRIPTION
**Pull request by HHeda**
Hello,
I recently used your tool to simulate circuits (amplifiers) with SNAILs in it. I changed it a bit so it can include a general purely inductive dipoles by specifying its terms in the Taylor series expansion of its inductive energy. I thought that you might be interested in these modifications I added, so here is a pull request. All this remains quite experimental, and I barely added a documentation, and there are no implemented tests yet. I can of course improve all this if you're interested in these new features.

Here are the main changes I made:

Allows to insert an arbitrary non linear inductive dipole (class D), taking into account at least orders 2 to 4 terms in the inductive energy expansion in series : the labels are the successive derivatives of this energy starting with order 2 (first relevant order).
It also calculates three waves mixing coefficients between modes to also get third order terms in the hamiltonian, in the same way than it is currently performed for anharmonicities.

The dipole is represented as a 'D' in a box in the GUI editor and as a black triangle in matplotlib.

A new function 'hamiltonian_sym' returns the full hamiltonian using sympy.physics.secondquant library.

The security preventing the user from giving too small or negative labels has been removed since higher order terms in the energy may be negative.

The arbitrary dipole can't have determined values, it has to be fully labelized.

Kind regards

### CODE REVIEW

**Comment by mgely** [comment]
Hi Hector, thanks for this contribution. I'm currently on holiday, but I'll definitely take a closer look at what you did when I get back (around the 17th of august).
Mario

**Comment by gsteele13** [comment]
Hey Mario, Did we ever pull this into the codebase? Christian from ETH was asking today if QuCAT can handle snails :) If so, it would be cool to bring this pull request into the codebase and also make a section of the docs showing how to use it with a SNAIL as an example

**Comment by gsteele13** [comment]
@HHeda Hi Hector, I'm picking this up and trying to merge it in (and also learning how git merging works...) 

In the meantime though, it would be great if you could include a short jupyter notebook demonstrating how to use this new element? For me to understand, but also to add it eventually to the docs. 

A notebook with some markdown explaining what you do, along with the accompanying circuit netlist file, would be great. (If you're not a notebook person, some commented python code would also be fine). Maybe in the example subfolder? 

In the meantime, I'll try to get the merge done, and if I don't hear back from you, I can probably also figure out the usage of this cool new element

**Review by gsteele13 — APPROVED** [review]
As far as I can tell (which is basically not at all?) this looks good...? I will approve it I guess, hopefully not everything breaks...

**Comment by gsteele13** [comment]
OK, I merged it into the master branch :)

**Comment by mgely** [comment]
Hi @gsteele13 @HHeda , sorry for not taking care of this pull request earlier...

@gsteele13 does raise a good point though, there are no examples supporting this code, and also not tests to show that it works. Tests (located in the test folder) are particularly important, not just to test that this code works now, but also, in case we modify this code in the future, to make sure we don't break anything. These tests are run automatically at each commit / pull request etc... This way of working is a bit slow, but inevitable for such a large codebase. I think it's good to keep the master and develop branch "clean", with code that has a few tests and that has some kind of an example.

I propose we put this code into a branch (note you can still pip install from a branch!) for the moment, until some tests and examples have been written. @HHeda, it would be really helpful if you could provide these examples and tests since you wrote the code. You can find info about how to do this here: https://qucat.org/devs/index.html, but if it's too much work,  it's also fine if you put these examples and tests in some temporary place in the repository, and I can integrate them into the testing code and website. There dosn't have to be that many tests. Typically I do a few calculations to which I know the answer, such that we can check that the code gives the right answer (and that a future change in the code didn't change that answer!). For the examples, a jupyter notebook in the style of the tutorials on the qucat website should work.

**Comment by mgely** [comment]
The branch is still here: https://github.com/HHeda/qucat/tree/arbitrary_dipole

**Comment by HHeda** [comment]
Hi !
I will work on it ! I just have to understand what I did, and I'll try to give you examples and tests as clean as possible.

**Comment by mgely** [comment]
Ah, thanks @HHeda !! And sorry for getting back to you so late.. I'm eager to see what your code can do, and cool that there is some demand as @gsteele13 mentionned, with people wanting to do SNAILs with QuCAT :)

**Comment by gsteele13** [comment]
@mgely Do we need to re-open this pull request somehow? I see you reverted it. If there is something I can do to help, let me know

**Comment by HHeda** [comment]
Hi, I just added a new tutorial (it has its own folder for now) in the tutorials folder of my arbitrary_dipole branch, showing how to use the new dipole feature with a SNAIL in a simple circuit. It requires a bit of preliminary code to use it correctly, but it works. No test yet, it could take me some time to do it correctly, but I'll try. Tell me if you need anything else, like an explanation about what I changed in the code for example, or any improvement of the tutorial if everything isn't clear.

**Comment by mgely** [comment]
Hi @HHeda, thanks for this! I think I will pull it into an arbitrary_dipole branch on the original qucat repo to put it into the website. I may re-organize things a little bit, but I'll ask you for you to review my changes before putting anything on the website don't worry.

About the tests, what I'll do is take out a few results from your tutorial and put them into the tests. If you have any other "sanity check" scripts, please send them over... You can commit them to the qucat arbitrary_dipole branch in any way which is handy for you, you can even just send them in this chat like 

```
a = 1+1
# a should be 2
```
and I can put that into the right format.
Don't feel obliged though, the tutorial is probably sufficient.

The easiest thing to get all this done is for me to give you "write" permissions on the qucat repo. So you can push to any branch (except the master branch), amongst other things. And you'll need permission from at least one other person to get a pull request into the master.

**Comment by mgely** [comment]
I gave @HHeda write permissions on the qucat repo.
I tried to create a branch containing these changes but couldn't copy all your changes over. I'm not sure why, but without write permissions to your fork it's difficult to diagnose. 
Could you create a branch on the qucat repo with your changes? Then I can work on getting them onto the website and into a new release.

**Comment by mgely** [comment]
Thanks!!

**Comment by HHeda** [comment]
Actually I did it in the wrong way, I just reverted my changes... I'll try something else

**Comment by mgely** [comment]
I just saw.. this is what I tried on sunday, to be honest I don't understand what goes wrong

**Pull request merged**
